apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-server
  namespace: actions-runner-system
spec:
  encryptedData:
    github_webhook_secret_token: AgApCJAiY7a7mdtb0dFbqgxzOIruNU6HAluFWSGPX8Ru/uY8pDIumLFP+mtuMzkMLG3AfypCjZoOY0U8a/h+NL807rNHt9OgmSohagqmc02etQRZGb0JIllLQwzzEUBrQLScqd3aYbiezBXacfoiM9H578ApcS+sBRegDyYUN0UT2jVan/X55v7dQO9KsURSVBw5iBXXcaj0SyT2IB9RP114tk965MC2awUnSmP+BhynoG/BUjOEEMabMpvYmYJn2c18XS4Xtu22F4E1qTHYM0JHBEpmzmh9TFtfFdSdThmPbKSu18SGfFcQfIULI56Z4zst/76PUxKXquLNGOfBo8T16tnb8Ujn3DgRWpX4tUsZ9s2LuIPiu2gCNKfkzCt+Jt4fyJM8OdwnNu1+IZ1eLT8G+0Y/buvRrXM+127VInEA6vTsABbifk5+xfJNz+AbyIBpRMunzK5L5fFbtKqI2HMIU3YwC5p1Xe/Gd2kOZs4BIrFj0eFkDjJrbok94Kl7Xx7IbY+birUIfzZiJurDFEXIo5GxlUgxV7njKDnjw2qENUBS1SIIOcqKvBj29YT8Qmaa2X1RQ9w290Z+RV56g4sUpVYLya7KIEacm6u4DYSHGFQ6szVlmT7eJa9EgpqNmt7F8UdoDr5+/dsLutZB0Ol29/pmPjMCXOEMQEZfKV67GHjyA3Ons67PtIwJDX54vqLsqh4snKRKmZvGSN6V95ohfhrpO1GJeNPhb54soTDw05n5bg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-webhook-server
      namespace: actions-runner-system

